### ISSUE TITLE
Filipino Translation

### ISSUE THREAD

**Issue by iam-strings** [AlecAivazis/survey#119]
Hi,

I would like to contribute on this project thru translation. I would like to translate the necessary files to Filipino thru GitHub in connection to Utopian Project.

Hoping for your response.

Thanks..

**Comment by AlecAivazis** [comment]
Hey @iam-strings - thanks for the offer!

I'm very interested in having multiple translations for the project's documentation. I'm a bit unclear on how this would work in practice however. Since the documentation is inline with the source code, where would the translated files live? I'm not familiar with the Utopian Project however some cursory googling found utopian.io which appears to pay people for translating documents - is this what you were referring to? If so, i'm also unclear where the money would come from.

**Comment by AlecAivazis** [comment]
@iam-strings i'm going to close this since it seems the issue has gone a bit stale. I'm still interested in translations of the docs, but am unclear on a few details. If you still want to contribute, please let me know and I can reopen the ticket.
