### ISSUE TITLE
Validate one value against another

### ISSUE THREAD

**Issue by Naatan** [AlecAivazis/survey#138]
I'm trying to validate two password entries against one another in one "survey", is this possible?

**Comment by AlecAivazis** [comment]
Hey @Naatan  - thanks for asking your question. Sorry it took me a few days to get back to you. I  had a hunch on a way to pull off what you were asking and just got enough time to verify that it works. It's not ideal but since the interface for `Validate` just takes the one reply and does not pass in the current answers, the only way you can do it is to reference the place you are writing all the values in the body of a validate function. I was able to modify the [doubleSelect](https://github.com/AlecAivazis/survey/blob/master/tests/doubleSelect.go) test like show to illustrate my point:

```golang
package main

import (
	"fmt"

	"gopkg.in/AlecAivazis/survey.v1"
)

func main() {
	answers := struct {
		Color  string
		Color2 string
	}{}

	var simpleQs = []*survey.Question{
		{
			Name: "color",
			Prompt: &survey.Select{
				Message: "select1:",
				Options: []string{"red", "blue", "green"},
			},
		},
		{
			Name: "color2",
			Prompt: &survey.Select{
				Message: "select2:",
				Options: []string{"red", "blue", "green"},
			},
			Validate: func(val interface{}) error {
				if str, ok := val.(string); ok && str != answers.Color {
					return fmt.Errorf("Does not match the first cohice")
				}

				return nil
			},
		},
	}

	// ask the question
	err := survey.Ask(simpleQs, &answers)

	if err != nil {
		fmt.Println(err.Error())
		return
	}
	// print the answers
	fmt.Printf("%s and %s.\n", answers.Color, answers.Color2)
}

```

**Comment by AlecAivazis** [comment]
@Naatan - i'm going to close this to keep things as tidy as possible. If the above recommendation does not work for you, please let me know and I can reopen it!

**Comment by Naatan** [comment]
Thanks @AlecAivazis, that works :)
