### ISSUE TITLE
Add a multiline input element

### ISSUE THREAD

**Issue by MarkusFreitag** [AlecAivazis/survey#151]
Sometimes you want the user to enter a list of things. Having a multiline input element would be ideal for such tasks.
Maybe it could be similar to this one: https://github.com/piotrmurach/tty-prompt#23-multiline

**Comment by AlecAivazis** [comment]
Hey @MarkusFreitag - thanks for the suggestion.

I have tried to keep the number of prompts very focused, hoping that the specialized prompts can be done a layer "above" survey. I like this prompt idea a lot but it can be pretty easily implemented as a `select`  over the current input prompt. If there is a big need for this prompt in a bunch of libraries, I am definitely not against adding it. 

I'm going to leave this issue open to see if other people want a similar prompt.

**Comment by MarkusFreitag** [comment]
Thanks for your feedback. The `select` element is only working when you already know the list of items, the user should choose from. In my use-case that is not the case.
My tool requires that the user specifies a list of serial numbers. Currently it is needed to put these serials into an input file. With a `multiline-input` element it would be possible without the need of an extra file.

P.S.: While looking through the `tty-prompt` gem, which was linked above, I find some other neat elements, such as the slider. Maybe you can give a short feedback, whether the number of elements should stay that focused. If so maybe we could think about something like `survey-advanced` to provide other, non basic elements.

P.P.S: Great library so far, it is really easy and fun to use =)

**Comment by AlecAivazis** [comment]
Whoops! Totally mistyped, sorry I have been kind of distracted. I meant to say that this suggestion could be accomplished with `input`, **not** a `select`.

**Comment by AlecAivazis** [comment]
Re, the more complicated prompts, I'm not against adding them to `survey` so long as they provide a unique experience and aren't implementable as a wrapper over an existing prompt.

**Comment by malexdev** [comment]
+1 to this request. I am currently having to use an `Editor` input for a user-provided change log.  It would be nice to be able to do this without having to open an external editor.

I can't use a bunch of `Input` requests because users need to be able to freely move around and edit lines they've typed.

I would be open to implementing and sending a PR if you feel my use case is too niche to implement at this time (or for any other reason), just let me know.  Basically, I'm willing to do the work unless it would be easy and fast for you to do. I'm the one requesting it after all.
