### ISSUE TITLE
Allow customization of QuestionIcon color

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#193]
It appears like if I set

    core.QuestionIcon = ">"

the `>` will still be printed in green currently.

So if I do something like:

    core.QuestionIcon = fmt.Sprintf("[ %s ]", color.RedString("?"))

the `[ ` part of my string is still printed as green.

That's why I think the color should be part of the `core.QuestionIcon` default value, so the default value actually should NOT be `?`, but rather: `color.GreenString("?")`.

Now to work this around I have to unset the color in my QuestionIcon string, like:

    $(RESET)[ $(RED)?$(END_RED) ]

which isn't ideal.

**Comment by MarkusFreitag** [comment]
Hi Ahmet,
the reason for this behaviour is, that survey uses the go templating engine under its hood. So the color is currently hardcoded in the specific templates. 
There is already an [issue](https://github.com/AlecAivazis/survey/issues/141), where we discussed to change this behaviour, so the user can set both (the icon and its color).
I already made a [proposal](https://github.com/MarkusFreitag/survey/commit/ceb60e1791ab3d800b1fe5957f246e3093900412), unfortunately we could not agree on a solution yet. Maybe we can move on in this issue.

**Comment by ahmetb** [comment]
My recommendation: Do not let users set colors.

Just let them give you a string like:

    "$(tput setaf 1) >$(tput sgr0)"

that they create with fatih/color pkg. This way you get out of color management.
Maybe you can add the "clear" sequence yourself so that the rest of the text (after indicator) uses default color.

**Comment by AlecAivazis** [comment]
Thanks for opening this issue @ahmetb! I think your original suggestion makes the most sense and Is an elegant API for setting the color and icon. It's a little unfortunate that you have to set both the icon and the color in order to change one of them, but it doesn't introduce any new API which is a huge win for me.

Since it might negatively affect the prompts of executables that are only setting the icon, I think its best to treat this as an API breaking change and include it alongside a few other changes in the upcoming `v2` release.

**Comment by AlecAivazis** [comment]
I'm going to close this since we already have a similar issue open. Thanks again for the suggestion @ahmetb!
