### ISSUE TITLE
feature request: survey.Select.FilterMessage: allow updating the filter tool tip?

### ISSUE THREAD

**Issue by turtleDev** [AlecAivazis/survey#198]
Hi !

I'm using `survey` for tooling at my company and some of the users seem to completely miss the filter functionality of `survey.Select`. I was hoping to update the tooltip on the right that says `[arrow to move, type to filter]` to something else.

I thought `survey.select.FilterMessage` would do just that, but instead it just shows up next to the `survey.Message`.

Thanks!

P.S. I'd love to help

**Comment by AlecAivazis** [comment]
Hey @turtleDev! 

I'm sorry that your user's are missing out on the filters - that's not good! There have been a few issues lately where people have said the tooltip messaging wasn't clear so I suspect your user's experience is common. I'd like to settle on something that makes it clear for all users. Do you have any ideas on specific text?

**Comment by turtleDev** [comment]
@AlecAivazis I actually think that the text is adequate. I just want the ability to be able to change it via configuration for a `survey.Select`. I know it contradicts what I said, but I think I may be able to experiment with a few different tooltips until I can find something that will help the user better understand the tools that they're using.

**Comment by AlecAivazis** [comment]
I don't think it's a good idea to allow that level of fine customization on the prompt. One of the design goals for `survey` is to provide as small of an API as possible since removing fields is much harder than adding them.  

I think your best option is to fork survey and experiment with the message. If you feel like you have something better and want to contribute it back, that would be awesome!
