### ISSUE TITLE
feature request: allow customization of Select/MultiSelect help message

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#234]
Customizing this message would be nice:

    [Use arrows to move, space to select, type to filter]

**Comment by AlecAivazis** [comment]
I'm curious what you would like to change it to? I have struggled for awhile with what these messages should say and you probably have a wide enough user base for something resembling user testing - have you had a chance to do anything like that?

I'm not sure if this level of fine-grain customizations make sure on a prompt-specific level 🤔

**Comment by ahmetb** [comment]
To me, mostly to unblock myself when the message is wrong. :)

Also could be for localization, but then it would need to apply to pretty much everything this library prompts for (errors, validations etc).

**Comment by AlecAivazis** [comment]
Yea I was thinking about localization too but that is a global configuration, not on a prompt level. I don't think adding this kind of configuration is a good idea.

Well you can always replace the contents of the template that the select uses. It's not a great API but since this is mostly for covering up bugs, I think that's fine.
