### ISSUE TITLE
glide support

### ISSUE THREAD

**Issue by sunshineGodd** [AlecAivazis/survey#235]
Hello:
      Do you plan to support glide? I use glide have error:
`[ERROR] Error scanning github.com/AlecAivazis/survey/v2: cannot find package "." in:
        /home/xxx/.glide/cache/src/https-github.com-AlecAivazis-survey/v2
`

**Comment by AlecAivazis** [comment]
Since we've adopted gomodules, i think it's on glide to understand the versioning in the import path. 

I don't know if `survey` should be responsible for integrating with all of the dependency management tools out there but if you know of an easy way to do so, I don't mind tweaking some things here or there as long as they don't break the gomodule imports

**Comment by sunshineGodd** [comment]
I think there are more code to change, or support go module first, thank you
