### ISSUE TITLE
Modify API to allow for non-string result from prompts?

### ISSUE THREAD

**Issue by coryb** [AlecAivazis/survey#31]
@AlecAivazis, creating an issue to track discussions started in [#28] and [#30] regarding potential API changes to encapsulate variable data returned from prompts (example: `MultiChoice` could return an `[]string` and `Confirm` could return a `bool`).

Thinking about your last suggestion, if I understand what you are saying the usage would look roughly like:
```
    var simpleQs = []*survey.Question{{
        Name: "name",
    }, {
        Name: "color",
    }, {
        Name: "days",
    }, {
        Name: "happy",
    }}

    answers := struct {
        Name  string
        Color string
        Days  []string
        Happy bool
    }{}

    err := survey.Ask(simpleQs, &answers)
```

Or more with tags:
```
    answers := struct {
        UserName   string   `survey:"name"`
        FavColor   string   `survey:"color"`
        PreferDays []string `survey:"days"`
        IsHappy    bool     `survey:"happy"`
    }{}

    err := survey.Ask(simpleQs, &answers)
```

How would we extend `AskOne` to work on interface values as well?  Perhaps something like:
```
days := []string{}
err := survey.AskOne(prompt, &days)
```

I think the usage of this is good from a user perspective.  However I think the implementation will be reasonably tricky though (ie lots of code) and we will need to do lots of reflection (which will potentially move some compile-time errors to runtime-errors).  So I think it is do-able but non-trivial, and I am not sure the implementation complexity cost would justify the relative ease of use in the API.

**Comment by coryb** [comment]
If we continue with the `Answer` field pattern in the prompt structs, I think we could achieve similar usage above, something like:
```
    answers := struct {
        UserName   string
        FavColor   string
        PreferDays []string
        AmHappy    bool
    }{}

    var simpleQs = []*survey.Question{{
        Prompt: &survey.Input{
            Answer: &answers.UserName,
        },
    }, {
        Prompt: &survey.Choice{
            Answer: &answers.FavColor,
        },
    }, {
        Prompt: &survey.MultiChoice{
            Answer: &answer.PreferDays,
        },
    }, {
        Prompt: &survey.Confirm{
            Answer: &answers.AmHappy,
        },
    }}

    err := survey.Ask(simpleQs)
    fmt.Printf("Answers: %v", answers)
```

The `AskOne` usage could look something like:
```
    p := &survey.Confirm{}
    err := survey.AskOne(p)
    fmt.Printf("Answer: %v", p.Answer)
```
or
```
    amHappy := false
    p := &survey.Confirm{
        Answer: &amHappy,
    }
    err := survey.AskOne(p)
    fmt.Printf("Answer: %v", amHappy)
```

The drawback of the `Answer` field is that perhaps it is not as intuitive as a `json.Unmarshal` type implementation, and it potentially requires a little bit more client code to wire the answers into named variables.    I do feel like the compile-time type safety is a big win with this approach though, and I think the code complexity in the libarary will be much less for this solution vs the `json.Unmarshal` style.

**Comment by coryb** [comment]
Probably worth noting that the `Validator` function prototype would probably have to change to something like for the `json.Unmarshal` style implementation:
```
type Validator func(interface{}) error
```
or this for the `Answer` field type implementation:
```
type Validator func(*Prompt) error
```
Both of these have drawbacks for any sort of generic validations such as `MaxLength`.

As a consumer of `survey` I think either the `json.Unmarshal` style or the `Answer` field solution would be fine.  There are perhaps other solutions but nothing is immediately coming to mind.

**Comment by AlecAivazis** [comment]
Wow @coryb thanks so much for writing this up! I really appreciate all the work you put into this (and the PRs). 

What you first outlined is exactly what I had in mind. I think your concerns about complexity are definitely valid. Once I finish the current project I'm working on, I will see how far that rabbit hole goes so we can accurately determine how much effort it will take. I think in the meantime, we can just keep the API slightly inconsistent since we seem to agree the "right thing" is the API based on reflection. Which, given thorough enough testing doesn't immediately scare me away. However, if it does end up being too much for to be worth it, then we can always go with the `Answer` api.

I will use this issue as a brain dump as I think about this more, but currently I much prefer the `json.Unmarshal` pattern so I'd like to play that out a bit before settling on alternatives.

**Comment by AlecAivazis** [comment]
Hey @coryb just wanted to let you know that I've begun working on the reflection-based API and am pretty hopeful. Here is the branch if you want to track my work: https://github.com/AlecAivazis/survey/tree/feat/v1

Regardless of this change, the work you said you were doing on `liveui` is orthogonal so I'm very curious to hear about that if you get something you like. I'm going to keep working on this and pass it to some people to get some feedback since this is the first time I've done something based on reflection but I wanted to also get your feedback. As it is now, the idea is that we will iterate over the list of `survey.Question`s, and pass the response to  `WriteAnswer` which will either change the appropriate field in a struct or just attempt to copy the value over if the target is not a struct.

**Comment by coryb** [comment]
okay, sounds good.  I am curious to see what you come up with for the reflection work.  I have done a bunch of reflection work, and I only sometimes regret it :)  The more I think about it the more I feel like the `Answer` field is might be a better way to go, or at least if I was maintaining this library I would probably go that way since it would not require reflection.  But I am curious to see how you get on with the refactor.

The `liveui` stuff has a few issues that would require fixing.  I think the `terminal` library you brought in solves some similar problems, so I think expanding on that solution probably makes the most sense.  Some of the stuff I am playing with now is abstracting/simplifying the prompt output (like merging the `MultiChoiceQuestionTemplate` with `MultiChoiceOptionsTemplate`) so that we only have one template per Prompt.  One of the prompting use-cases I have is to add something like `[? for help]` to a prompt to allow a user to get a detailed help message dynamically. In order to do that I think I need to simplify how prompt output/updating is done.  So anyway, I am tweaking some printing code now, but not happy with any of the solutions yet.

**Comment by AlecAivazis** [comment]
Hey cory, that branch has a fully working version of the new API if you want to take it for a spin. Just writing some documentation and then i'll submit a PR for testing and review. It didn't end up being that complicated so I'm slightly worried that I've oversimplified the implementation but some manual testing, as well as the unit tests, seem to indicate things are working and are relative "safe". This might just be because my background is in dynamic languages, but the runtime cost seems to be worth the improved API. Also as I think about it more and more, our problem mirrors `json.Unmarshal` really closely and I think solving it a similar way feels the most "idiomatic" (whatever that means).

**Comment by coryb** [comment]
Hey, looks promising.  What are your thoughts on non-string type prompts?  I think this code will panic/error on the string->int conversion and would always fail the Validate function ...

```
    var simpleQs = []*survey.Question{
        {
            Name: "age",
            Prompt: &survey.Input{
                Message: "What is your age?",
            },
            Validate: survey.Required,
        },
    }
    answers := struct {
        Age int
    }{}
    err := survey.Ask(simpleQs, &answers)
```

**Comment by AlecAivazis** [comment]
Yea that is an unfortunate side effect of moving the type checking to the runtime environment. The most we can hope for is to provide very clear error messages which I can definitely improve on. One good note is that the type "casting" will always fail so as long as the user runs their code once, they should be able to verify that the typing matches.

We'll have to add some documentation for the various validators to list which types they act on. Fortunately, writing validators when you know the prompt is relatively easy because you can assume the type assertions will pass. Unfortunately, that means that validators like `Required` got a little complicated but I think what I have works, please let me know if you run into any bugs.

**Comment by AlecAivazis** [comment]
To answer your question, I think generalising the return type of a prompt beyond strings is a good idea since it opens a lot of possibilities for the future. Also, forcing a single type (string) for the prompts is the original problem we were trying to solve because `MultiSelect` naturally wants to return multiple values and this approach still seems like the best way to avoid any other sort of type assertions by the user, even if they have to be a bit careful.

**Comment by coryb** [comment]
Okay, cool.  I think it is reasonable to punt on the implicit type conversions, easy enough for users to do the validation/conversion in their code.  Something else that comes to mind (which you may not want to support) is:
```
    answers := make(map[string]interface{})
    err := survey.Ask(simpleQs, &answers)
```
I think this is supported by `json.Unmarshal`, but can't say it would be the recommended usage.  Not something I am likely to use, just a thought.

**Comment by AlecAivazis** [comment]
Yea I was thinking about supporting that, was curious to hear your thoughts. Since you brought it up I think other users might expect it although I'm partial to having only one way to do something to avoid supporting two different APIs. Probably something we can punt on for now too

**Comment by coryb** [comment]
Yeah, probably makes sense to wait for a user to request that feature before introducing it, it generally leads to bad practices (ie tons of type casting in client code).  So with those minor caveat's I think what you have looks pretty good.

**Comment by AlecAivazis** [comment]
Closing this since #34 was merged
