### ISSUE TITLE
not selected / out of focus icon option

### ISSUE THREAD

**Issue by quiquelhappy** [AlecAivazis/survey#371]
Hello,
I think I'd be great if there was an unselected / out of focus icon option option icon, as there is only an option for SelectFocus right now

**Comment by mislav** [comment]
Thanks for the suggestion! I don't think this is something that we'll provide in Survey since it would make the implementation more complex but I don't believe it would be widely used.

You could override the `SelectQuestionTemplate` in your application to achieve what you wish. Just copy over the template string from this repository and tweak it with your own rendering preferences.
