### ISSUE TITLE
Input only returns string

### ISSUE THREAD

**Issue by jdoklovic** [AlecAivazis/survey#68]
So, although the write tests handle different answer types, when you go up a level to the ask / askOne functions, they will always fail if you do a simple Input{} prompt with anything but a string.

given this test code:
```go
func TestInt(t *testing.T) {
	q := []*Question{
		{
			Name: "age",
			Prompt: &Input{
				Message: "What is your age?",
			},
			Validate: Required,
		},
	}

	in, _ := ioutil.TempFile("", "")
	defer in.Close()

	os.Stdin = in

	io.WriteString(in, "21\n")
	in.Seek(0, os.SEEK_SET)

	ans := int64(0)

	err := Ask(q, &ans)

	assert.Nil(t, err)
	assert.Equal(t, int64(21), ans)

}
```
you'll always get an error "reflect.Set: value of type string is not assignable to type int64"
I believe it's due to the fact that Input.Prompt always converts stuff to strings at the end:
```go
// we're done
	return string(line), err
```
So essentially, if you use Input you always have to expect a string back, unless i'm missing something.

**Comment by jdoklovic** [comment]
If this is indeed true, I would suggest either putting all of that type conversion in, OR refactoring the library to explicitly deal with strings to make it less confusing.

**Comment by AlecAivazis** [comment]
Thanks for another issue @jdoklovic! 

Indeed, you are correct that at the moment `Input` will always return a `string`. I tried to document this in the README but I need to do more work detailing these "constraints". I am personally a fan of keeping survey simple and pushing any sort of type assertion/casting logic outside (beyond what was necessary to support prompts like `MultiSelect` and `Confirm`) but i will continue to think about wether this belong in survey or not. 

Since you are the first person to request it, i'm inclined to hold of on more large refactoring that introduces more logic in the background. You should be able to use the string conversion you showed me earlier in order to satisfy your immediate use case. If more people ask for this sort of conversion, we can revisit what sort of type semantics belong in `survey` as a whole.

**Comment by jdoklovic** [comment]
It's fine if it only deals with strings, but if that's the case, it's currently super painful to do the type stuff at a higher level. I'll try to send you some code illustrating what i have to do in a bit

**Comment by AlecAivazis** [comment]
I'm going to close this now since the prompts should be converting to whatever type is handed to them. Thanks again for all the work with the type conversions!
