### ISSUE TITLE
Choice questions with less than 3 options leave first line

### ISSUE THREAD

**Issue by mholt** [AlecAivazis/survey#7]
Neat little package, thanks!

Unfortunately, when choice questions have just 1 or 2 options, the first line remains:

```go
package main

import (
    "fmt"
    "github.com/alecaivazis/survey"
)

// the questions to ask
var qs = []*survey.Question{
    {
        Name: "color",
        Prompt: &survey.Choice{
            Message: "Choose a color:",
            Choices: []string{"red", "blue"},
            Default: "red",
        },
    },
}

func main() {
    answers, err := survey.Ask(qs)

    if err != nil {
        fmt.Println("\n", err.Error())
        return
    }

    fmt.Printf("%s chose %s.", answers["name"], answers["color"])
}
```

Prints, at the end:

```plain
? Choose a color:
? Choose a color: red
 chose red.
```

**Comment by AlecAivazis** [comment]
Wow thanks for the issue reports! I was not expecting this at all. 

I was 100% sure there were going to be crazy edge cases but was focusing on other projects because I wasn't sure this was used. I'd gladly take a look at this this weekend and let you know. I wish I knew of a way I could test the terminal for outputs, it would make writing this library much easier...

**Comment by mholt** [comment]
Just looking through the code for anything related to "2" and number of lines [this segment](https://github.com/AlecAivazis/survey/blob/f3dba3b79c12ec8ea5363333e3ae1065b902f8eb/input.go#L47-L52) might be culprit, although I haven't performed any analysis or debugged it. Just an idea for a place to look into.
