### ISSUE TITLE
MultiSelect fails to render a long list

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#70]
Below you can see a picture of a long list passed to MultiSelect. Issues:

- default view is the end of the list, even though the cursor is by default at item 0.
- keeps showing only the end of list no matter where the cursor is moved to.
    - never shows the earlier items. I tried bringing cursor all the way to the end and tried to bring it above Item 102. It never showed Item 101 or things before it.

![image](https://user-images.githubusercontent.com/159209/27660092-b5dfd0b8-5c0a-11e7-8262-119eacf00f6a.png)

MultiSelect should:
- adapt to the dynamic terminal height
- slide the options window displayed along with the cursor

**Comment by ahmetb** [comment]
@AlecAivazis I recommend looking at Inquirer.js `examples/long-list.js`. It does not use all of the screen height to list the options, but offers a sliding window in e.g. 7 rows:

![](http://g.recordit.co/2rgsxcNvkN.gif)

It could be offered as an option, it's not really necessary to me at least.

**Comment by AlecAivazis** [comment]
@ahmetb thanks for the screenshots and pointing me to the example in inquirer. I'm not sure about the specific details of their implementation but my thinking is this - add a pageSize option to Select and MultiSelect and then show the minimum of that number and the terminal height. that way even if the developer specified a large number because the list is long, but the user has a terminal that is short, there isn't any potential for lost information (say if they turned a scrollback off

**Comment by ahmetb** [comment]
Yeah that's tricky. I'd play with Inquirer to see how they handle this case if you want to get closer to their implementation.

**Comment by AlecAivazis** [comment]
@ahmetb as of the `v1.2.0` tag, the selects and multi-selects should be paginated with a default value of 7 - lemme know if you run into any more issues
