### ISSUE TITLE
Provide more examples, for all question types

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#82]
I was trying to use MultiSelect and tried to look for code examples, mostly because it's unclear to me how I'm supposed to collect the answers back (what `interface{}`'s actual type should be).

I tried `[]string`, didn't work. So I had to dig into [`examples/longlist.go`](https://github.com/AlecAivazis/survey/blob/master/examples/longlist.go), where I saw a survey.Select example. Apparently it deserializes into a `struct` that has a field that has the same name as `question.Name`. This sounds fine. 

But I _have to guess_ whether that field should be `[]int` or `[]string` because it's not documented at https://godoc.org/github.com/AlecAivazis/survey#MultiSelect and I can't find any examples. It seems like there's a little bit of friction or docs/examples gap.

**Comment by ahmetb** [comment]
Please ignore the "I tried []string, didn't work" part. It was a validation error on my part (opening a separate issue).

**Comment by AlecAivazis** [comment]
I'm not sure what sort of documentation you have in mind - I tried to document what the expected input was in the readme in the example for each prompt. I can try to put more information in the comment so that godocs picks it up, does that work for you? If you have a better idea for documentation, i'd love to review a PR if you submitted one 😉

**Comment by AlecAivazis** [comment]
I"m going to close this - if you feel like I should add more documentation, please open another ticket :)
