### ISSUE TITLE
Support []int for writing indexes in addition to []string

### ISSUE THREAD

**Issue by ahmetb** [AlecAivazis/survey#84]
The use case I have is `type Product struct { name string, code int }`.

So I create a `var productNames []string` from my `[]product` slice, then pass it to survey.AskOne as `MultiSelect` options:

```go
if err := survey.AskOne(&survey.MultiSelect{
	Message: "Which products do you want: ",
	Options: productNames,
}, &productAnswers, nil); err != nil {
	log.Fatal(errors.Wrap(err, "failed to prompt"))
}
```

At the end what I need is a list of `product.code`s.

In the code above, `productAnswers` has to be `[]string`. To find the relevant `product` value that has the name displayed in the options list, I have to do either of the following:

- create a name to product (`map[string]product`) mapping and after getting answers, look it up from there.
- for each answer, iterate over `products` and find the product that has name==answer.

Both are fine as the list is probably small and these are cheap operations, they just cause extra code to be written.

If `survey` package supported writing indexes to `[]int`s, it would be really easy to look the actual structs up from the `products`  slice. For example, https://github.com/abiosoft/ishell package returns the answers to MultiSelect as slice of indexes chosen, and it works fine too. So if Write() function copying the answers into value supported both []int and []string for MultiSelect, it would be great.

**Comment by AlecAivazis** [comment]
Hey @ahmetb thanks for the detailed use case, I'm personally not a fan of returning an index from the list of options in a multi select prompt because i think it would create 2 different ways of retrieving data from a multi select which I think unnecessarily overcomplicates the API. Instead would like to add support for `[]int` in the case where the options are `[]string{"1", "2", "3"}` and the answers would then be converted to the right types. 

I recnogize this doesn't solve your issue so let I suggest implementing the interface described [here](https://github.com/AlecAivazis/survey#custom-types) and put the transformation from a list of strings to products in the interface method.

**Comment by AlecAivazis** [comment]
Another feature that could be added to support your usecase is having an object that allows for a different displayed question from the one that is returned by the prompt. This could look like

```
survey.MultiSelect{
    Message: "which products do you want?",
    Options: {}survey.Option{
        {Display: "ProductName1", Value: 123},
        {Display: "ProductName2", Value: 514},
    }
}
```

**Comment by ahmetb** [comment]
Your suggestion sounds interesting, how about instead of a well defined struct, accepting something like `[]fmt.Stringer` (or `[]survey.Option` , which would be an interface that requires `func DisplayName() string`?

In your example, I would probably use `Value` to store indexes.

**Comment by AlecAivazis** [comment]
@ahmetb i'm going to close this now since the `settable` interface is now merged. Also, #92 should handle the `int` ->  `string` conversions in the deeply nested cases (as in the `MultiSelect` example you shared above)
