### ISSUE TITLE
Use more compatible symbols by default

### ISSUE THREAD

**Issue by Noah-Huppert** [AlecAivazis/survey#93]
The default [customization option values](https://github.com/AlecAivazis/survey#customizing-output),  while nice looking, are not extraordinarily compatible with the average user's font face. This is especially relevant for a library like survey. Which will probably be used in applications which interact with less technical users.  

It would be nice if survey shipped with some more compatible defaults:

```golang
core.ErrorIcon = "X"
core.HelpIcon = "????"
core.QuestionIcon = "?"
core.SelectFocusIcon = ">"
core.MarkedOptionIcon = "[x]"
core.UnmarkedOptionIcon = "[ ]"
```

They still end up looking pretty nice looking:

![2017-09-07-150747_1920x1080_scrot](https://user-images.githubusercontent.com/3323504/30180644-91416ba2-93de-11e7-93f4-61e604713655.png)

**Comment by AlecAivazis** [comment]
That's a good point @Noah-Huppert. I definitely see the reason for `survey` to err on the side of compatibility here and use "icons" that are supported by any terminal. If people want something fancier, they are always able to change it themselves. If you want to submit a PR, I would gladly look it over, otherwise, I'll try to get something out this weekend.

**Comment by AlecAivazis** [comment]
Since I'm on a windows machine, I figured I would leave a note that this also affects the standard `cmd.exe` terminal on windows and results in a pretty ugly experience.
<img width="274" alt="capture" src="https://user-images.githubusercontent.com/916317/31804459-5bc8387e-b50e-11e7-95a8-f6264875d4fd.PNG">

**Comment by AlecAivazis** [comment]
Closing this since #150 addresses it
