### ISSUE TITLE
Is there a way to pass a different value on a Select prompt?

### ISSUE THREAD

**Issue by mattstratton** [AlecAivazis/survey#98]
I have a Select prompt, and would like to display one thing to the user, but return a different value than what is being displayed.

That is to say, it will show "George Bluth", but would like it to instead return the value of "george-bluth", which is something i could have in a map, let's say.

In this particular case, I can transform the value myself (since it's simple toLower and string replacement), but in other cases it might be more arbitrary.

**Comment by Frodgy** [comment]
Yeah, it would be much better to pass an array as options to return an index of answer.

**Comment by AlecAivazis** [comment]
Hey @mattstratton! Currently there isn't a way to do this. I've been trying to think of the right API to support this. One approach would be to have another interface similar to `settable` which is described [here](https://github.com/AlecAivazis/survey#custom-types) which could be passed to the select. Or we could change the option to a struct instead of string to store the two values. 

What do you think?

Also,@Frodgy  FWIW, `Select` doesn't pass an index (nor `MultiSelect` a slice) so that a user could use a `Select`/`MultiSelect` to collect intsor an int slice depending. If you strongly think this should be changed, let's open up a ticket! I'd love to discuss it some more.

**Comment by Frodgy** [comment]
@mattstratton, didn't you just say, that it would be a good idea to use struct to store more values instead of one string? At least, I got a case, when you have to select a book from an array, so with your interesting "survey" thing it goes in a really fancy way, except the dirty moment, when I have to search the returned string from survey across the whole book array.

**Comment by dpastoor** [comment]
Couldn't you just add a `Callback` to the Question struct, similar to the Validator, that would be invoked like middleware.

```go
[]*survey.Question{
    {
        Name:     "name",
        Prompt:   &survey.Input{Message: "What is your name?"},
        Validate: survey.Required,
        Callback: func (val string) string {
                              return strings.ToLower(val)
                         },
    },...
```

**Comment by Frodgy** [comment]
@dpastoor, is it real to use to validators at the same time? Like Required and MinLength(n)?

**Comment by dpastoor** [comment]
that is something for @AlecAivazis to answer. Mine was just a hypothetical example, in which I pulled the survey.Question from the readme and added the Callback (hypothetical) extension.

**Comment by AlecAivazis** [comment]
@dpastoor I was pretty certain I added a `Transform` field to questions which allow for the value to change after being submitted but apparently, I'm just going crazy. I think that's the simplest approach. If you want to submit a PR, it should be pretty easy to test and implement. I would love to look it over.

Also, @Frodgy I have a few scripts that use survey and in both of them I use `survey.ComposeValidators` to combine a bunch of validators into one. Specifically, I use it to set both a minimum and max length for a given response.

**Comment by dpastoor** [comment]
@AlecAivazis I'm swamped right now, but will be circling back to a project and will likely use this lib at the end of the year. If this hasn't been implemented by then I can probably take a crack at it.

**Comment by kataras** [comment]
Hello guys,

@mattstratton and @Frodgy  Nice feature request.
@dpastoor Good example but we needed something that would receive an `interface{}` and returns an `interface{}` instead of `string`, note that answers can be any type.

@AlecAivazis you had that idea back in 2016 as well, at https://github.com/AlecAivazis/survey/issues/4 but you never implemented that for unknown reasons 🤓 

So I took the chance to implement the `Transform` which covers all the above.

- The `Transform` has the simple form of `func(answer interface{}) (newAnswer interface{})`.
- We have three helpers for string values as well.
- The simple example on "what is your name", it's a good use case of the `survey.Title` _Transformer_, so I took the liberty to update that as well (both README.md and examples/simple.main.go).
- With the `TransformString(func(string)string) Transformer` helper the end-developer can pass any compatible function like the std's `strings.ToUpper` and e.t.c..

## A simple showcase

![1](https://user-images.githubusercontent.com/22900943/31803091-81e1925c-b55a-11e7-972a-dba73dfcef26.png)

![2](https://user-images.githubusercontent.com/22900943/31803092-8205a8d6-b55a-11e7-9896-e22bceb3c66e.png)

> shown immediately

![3](https://user-images.githubusercontent.com/22900943/31803093-8227649e-b55a-11e7-850f-75c3832b97e9.png)

Hope that I helped you a little, @AlecAivazis keep up the nice work here, it's really one of the best common-usage Go library in my opinion. _Have Fun!_

**Comment by kataras** [comment]
Hello guys,

@mattstratton and @Frodgy  Nice feature request.
@dpastoor Good example but we needed something that would receive an `interface{}` and returns an `interface{}` instead of `string`, note that answers can be any type.

@AlecAivazis you had that idea back in 2016 as well, at https://github.com/AlecAivazis/survey/issues/4 but you never implemented that for unknown reasons 🤓 

So I took the chance to implement the `Transform` which covers all the above.

- The `Transform` has the simple form of `func(answer interface{}) (newAnswer interface{})`.
- We have three helpers for string values as well.
- The simple example on "what is your name", it's a good use case of the `survey.Title` _Transformer_, so I took the liberty to update that as well (both README.md and examples/simple.main.go).
- With the `TransformString(func(string)string) Transformer` helper the end-developer can pass any compatible function like the std's `strings.ToUpper` and e.t.c..

## A simple showcase

![1](https://user-images.githubusercontent.com/22900943/31803091-81e1925c-b55a-11e7-972a-dba73dfcef26.png)

![2](https://user-images.githubusercontent.com/22900943/31803092-8205a8d6-b55a-11e7-9896-e22bceb3c66e.png)

> shown immediately

![3](https://user-images.githubusercontent.com/22900943/31803093-8227649e-b55a-11e7-850f-75c3832b97e9.png)

Hope that I helped you a little, @AlecAivazis keep up the nice work here, it's really one of the best common-usage Go library in my opinion. _Have Fun!_

------

The PR: https://github.com/AlecAivazis/survey/pull/104

**Comment by kataras** [comment]
Hello guys,

@mattstratton and @Frodgy  Nice feature request.
@dpastoor Good example but we needed something that would receive an `interface{}` and returns an `interface{}` instead of `string`, note that answers can be any type.

@AlecAivazis you had that idea back in 2016 as well, at https://github.com/AlecAivazis/survey/issues/4 but you never implemented that for unknown reasons 🤓 

So I took the chance to implement the `Transform` which covers all the above.

- The `Transform` has the simple form of `func(answer interface{}) (newAnswer interface{})`.
- We have three helpers for string values as well.
- The simple example on "what is your name", it's a good use case of the `survey.Title` _Transformer_, so I took the liberty to update that as well (both README.md and examples/simple.go).
- With the `TransformString(func(string)string) Transformer` helper the end-developer can pass any compatible function like the std's `strings.ToUpper` and e.t.c..

## A simple showcase

![1](https://user-images.githubusercontent.com/22900943/31803091-81e1925c-b55a-11e7-972a-dba73dfcef26.png)

![2](https://user-images.githubusercontent.com/22900943/31803092-8205a8d6-b55a-11e7-9896-e22bceb3c66e.png)

> shown immediately

![3](https://user-images.githubusercontent.com/22900943/31803093-8227649e-b55a-11e7-850f-75c3832b97e9.png)

Hope that I helped you a little, @AlecAivazis **keep up the nice work here**, it's really one of the best common-usage Go library in my opinion. _Have Fun!_

------

The PR: https://github.com/AlecAivazis/survey/pull/104

**Comment by kataras** [comment]
Hello guys,

@mattstratton and @Frodgy  Nice feature request.
@dpastoor Good example but we needed something that would receive an `interface{}` and returns an `interface{}` instead of `string`, note that answers can be any type.

@AlecAivazis you had that idea back in 2016 as well, at https://github.com/AlecAivazis/survey/issues/4 but you never implemented that for unknown reasons 🤓 

So I took the chance to implement the `Transform` which covers all the above.

- The `Transform` has the simple form of `func(answer interface{}) (newAnswer interface{})`.
- We have three helpers for string values as well.
- The simple example on "what is your name", it's a good use case of the `survey.Title` _Transformer_, so I took the liberty to update that as well (both README.md and examples/simple.go).
- With the `TransformString(func(string)string) Transformer` helper the end-developer can pass any compatible function like the std's `strings.ToUpper` and e.t.c..

## A simple showcase

![1](https://user-images.githubusercontent.com/22900943/31803091-81e1925c-b55a-11e7-972a-dba73dfcef26.png)

![2](https://user-images.githubusercontent.com/22900943/31803092-8205a8d6-b55a-11e7-9896-e22bceb3c66e.png)

> shown immediately

![3](https://user-images.githubusercontent.com/22900943/31803093-8227649e-b55a-11e7-850f-75c3832b97e9.png)

Hope that I helped you a little, @AlecAivazis **keep up the nice work here**, it's really one of the best common-usage Go libraries in my opinion. _Have Fun!_

------

The PR: https://github.com/AlecAivazis/survey/pull/104

**Comment by AlecAivazis** [comment]
Hey @kataras! Thank you so much for the kind words. I'm very happy to hear that you find `survey` so useful. Also, thinking about it more, I probably closed that issue when support was added for custom logic when writing to a specific type. Although, I can understand how these are two different use cases.

Thanks for submitting the PR - i'll start reviewing it now.

**Comment by kataras** [comment]
Hello @AlecAivazis, I just woke up. Yes, `Validator` and `Transform` are different things and should kept as they are, I firstly though that we may return a second output parameter `error` on the `Transformer` and remove the `Validator` but with a little more though this is not a good idea, is simpler to have different types for different use cases.

**Comment by AlecAivazis** [comment]
@mattstratton - thanks to @kataras, you can now transform the value using the `Transform` field of a question. I'm going to close this to keep things tidy. Please let me know if any other problems pop up!
